[project]
name = "paper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentgit",
    "agno>=2.2.1",
    "autogen>=0.10.0",
    "autogen-agentchat>=0.7.5",
    "autogen-core>=0.7.5",
    "autogen-ext[openai]>=0.7.5",
    "dotenv>=0.9.9",
    "fastapi>=0.120.0",
    "langfuse>=3.8.1",
    "langgraph-checkpoint-sqlite>=2.0.11",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.44",
]

[tool.uv.sources]
agentgit = { path = "agentgit-0.0.2-py3-none-any.whl" }
